//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight_BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatabaseSize
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Size { get; set; }
        public decimal Used_Space_MB { get; set; }
        public decimal Free_Space_MB { get; set; }
        public decimal PercentFree { get; set; }
        public string Updateability { get; set; }
        public string StateDesc { get; set; }
        public System.DateTime RunDate { get; set; }
        public int RunCount { get; set; }
        public int InstanceId { get; set; }
    
        public virtual Instance Instance { get; set; }
    }
}
