//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight_BL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InsightEntities : DbContext
    {
        public InsightEntities()
            : base("name=InsightEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Instance> Instances { get; set; }
        public virtual DbSet<InstanceDetail> InstanceDetails { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobLog> JobLogs { get; set; }
        public virtual DbSet<DatabaseOption> DatabaseOptions { get; set; }
        public virtual DbSet<Backup> Backups { get; set; }
        public virtual DbSet<Drive> Drives { get; set; }
        public virtual DbSet<DatabaseFile> DatabaseFiles { get; set; }
        public virtual DbSet<DatabaseSize> DatabaseSize { get; set; }
        public virtual DbSet<UserMembership> UserMembership { get; set; }
        public virtual DbSet<LoginMembership> LoginMembership { get; set; }
        public virtual DbSet<LogSize> LogSize { get; set; }
    }
}
