//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight_BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobLog
    {
        public int Id { get; set; }
        public System.DateTime RunDate { get; set; }
        public int RunCount { get; set; }
        public int JobId { get; set; }
        public string Type { get; set; }
        public string Message { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
